In [24]:
import numpy as np
import pandas as pd

df = pd.read_csv('../data/simple_loan.csv')

In [25]:
df.head()

age  employed own_house credit target
0  young     False         n   fair     no
1  young     False         n   good     no
2  young      True         n   good    yes
3  young      True         y   fair    yes
4  young     False         n   fair     no

In [26]:
df.shape

(17, 5)

In [27]:
df.groupby('target').count()

age  employed  own_house  credit
target                                  
no        6         6          6       6
yes      11        11         11      11

ทำตามรางสรุปสถานะการมีงานทำ

In [28]:
pd.pivot_table(index='employed',columns=['target'], values=['age'],
               data=df,aggfunc='count', fill_value=0, margins=True)

age        
target    no yes All
employed            
False      6   5  11
True       0   6   6
All        6  11  17

In [29]:
# ws02

feature_columns = ['age', 'employed', 'own_house', 'credit']
X = df[feature_columns]
X.head()

age  employed own_house credit
0  young     False         n   fair
1  young     False         n   good
2  young      True         n   good
3  young      True         y   fair
4  young     False         n   fair

In [30]:
y = df.target
y.head()

0     no
1     no
2    yes
3    yes
4     no
Name: target, dtype: object

In [31]:
df.columns

Index(['age', 'employed', 'own_house', 'credit', 'target'], dtype='object')

In [32]:
def labelEncode(data, columns):
    for i in columns:
#         print(i)
        data[i + '_'], _ = pd.factorize(data[i], sort=True)

feature_columns = ['age', 'employed', 'own_house', 'credit']
labelEncode(df, feature_columns)

In [33]:
df['target_'], class_names = pd.factorize(df.target)
df.sample(5)

age  employed own_house     credit target  age_  employed_  own_house_  \
1    young     False         n       good     no     2          0           0   
4    young     False         n       fair     no     2          0           0   
11     old     False         y       good    yes     1          0           1   
7   middle      True         y       good    yes     0          1           1   
8   middle     False         y  excellent    yes     0          0           1   

    credit_  target_  
1         2        0  
4         1        0  
11        2        1  
7         2        1  
8         0        1

In [34]:
class_names

Index(['no', 'yes'], dtype='object')

In [35]:
enc_columns = ['age_', 'employed_', 'own_house_', 'credit_']
X = df[enc_columns] 

X.head()
X.sample(4)


age_  employed_  own_house_  credit_
13     1          1           0        0
10     1          0           1        0
1      2          0           0        2
3      2          1           1        1

In [36]:
y = df.target_
y[:5]

0    0
1    0
2    1
3    1
4    0
Name: target_, dtype: int64

In [37]:
for i in enc_columns:
#     print(i)
    print(i[:-1]) # item
    print(' ',df[i[:-1]].unique())
    print(' ',df[i].unique())
    print('  -------')

age
  ['young' 'middle' 'old']
  [2 0 1]
  -------
employed
  [False  True]
  [0 1]
  -------
own_house
  ['n' 'y']
  [0 1]
  -------
credit
  ['fair' 'good' 'excellent']
  [1 2 0]
  -------


In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=20) 


In [39]:
X_train.shape , X_test.shape

((11, 4), (6, 4))

In [40]:
y_train.shape , y_test.shape

((11,), (6,))

In [41]:
X_train.head()

age_  employed_  own_house_  credit_
13     1          1           0        0
0      2          0           0        1
2      2          1           0        2
7      0          1           1        2
6      0          0           0        2

In [42]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [43]:
model.score(X_test, y_test)

1.0

In [44]:
X_input = [[0,1,1,1], [1,0,0,2], [1,1,0,1], [2,0,1,1]]
y_predict = model.predict(X_input)
print(y_predict)

for i in y_predict:
    print('Result : {}'. format(class_names[i]))


[1 0 1 1]
Result : yes
Result : no
Result : yes
Result : yes


E:\work\machine_learing101\venv\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [45]:
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

cvs = cross_val_score(model, X, y, cv=5)  
print('cross val scores {}'.format(cvs))
print('mean {:4f}' .format(cvs.mean()))

cross val scores [1.         1.         1.         1.         0.66666667]
mean 0.933333
